adminUser:
  password: local:pegasus/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: craft.de.jet@gmail.com
  token: local:pegasus/pipelineUser:token
  username: craft-de-jet
prow:
  hmacToken: local:pegasus/prow:hmacToken
